language: node_js
node_js:
  - "6.11.5"
notifications:
  email:  
     recipients:
       -  gonzalpetraglia@gmail.com
       -  santiago.v.gandolfo@gmail.com
       -  federicobalina@gmail.com
       -  christiangelone@gmail.com
     on_failure: always 
     on_success: change
install: "npm install"
script: 
  ng build && npm run server-test
after_success:
   npm run coveralls